# 刷流配置
[brush]
# 刷流任务工作时间范围设置
# 格式说明:
# - "1-4" 表示每天凌晨1点00分到4点59分工作
# - "12-18" 表示每天12点00分到18点59分工作
# - "20-23,0-6" 表示每天20点00分到23点59分以及0点00分到6点59分工作
# 留空则表示24小时工作
work_time = ""


# 保留最小剩余磁盘空间，支持以下格式:
# - 纯数字 (默认单位为B)
# - "1KiB", "1MiB", "1GiB", "1TiB" 
# 默认值为 1024GiB
min_disk_space = "1024GiB"

# 位于下载状态的种子数上限，当qb中下载状态种子数大于此值时不会添加新的任务
max_downloading_torrents = 6  

# 平均速度计算用的时间周期，默认即可，不推荐修改
upload_cycle = 600  # 平均上传速度计算周期，单位秒，默认600秒即10分钟 
download_cycle = 600 # 平均下载速度计算周期，单位秒，默认600秒即10分钟

# 期望达到的整体上传速度，支持以下格式:
# - 纯数字 (默认单位为B/s)
# - "1KiB/s", "1MiB/s", "1GiB/s"
# 推荐设置为上传速率的50%，比如:30Mbps带宽最大上传速度为3.75MiB/s，推荐设置为"1.875MiB/s"
expect_upload_speed = "1.875MiB/s"

# 期望达到的整体下载速度，支持以下格式:
# - 纯数字 (默认单位为B/s)
# - "1KiB/s", "1MiB/s", "1GiB/s"
# 一个时间周期内的最大下载速度大于此值的情况下，不会添加新的任务
# 为什么要有这个逻辑， 因为我发现QB中如果有正在下载的任务且下载速度较快达到了12MiB/s，那么其他正在上传的种子会受到影响上传速度会降低很多。
# 当但下载任务完成时或下载速度放慢时，其他正在上传的种子会恢复正常上传速度。
# 因此，当下载速度达到一定值时，不再添加新的任务，避免下载任务过多导致上传速度降低。直到下载速度降低后一段时间，上传速度还没有达标再进行添加新的任务。
expect_download_speed = "12MiB/s"

# 单个种子的文件大小限制，支持以下格式:
# - 纯数字 (默认单位为B)
# - "1KiB", "1MiB", "1GiB", "1TiB"
# 超过此限制后，会将种子中的部分文件设置为不下载
# 一般不需要修改
torrent_max_size = "50GiB"

# 允许种子最大的无活跃(无下载也无上传)时间，超过此时间将会被删除，单位为:小时，默认24
max_no_activate_time = 24

# 下载器设置，仅支持qb
[downloader]
url = "http://127.0.0.1:8080"
username = ""
password = ""

# M-Team配置示例，请自行替换x-api-key参数
[[sites]]
name = "M-Team"
[[sites.headers]]
key = "x-api-key"
value = "xxxxx"

